### ISSUE TITLE
numpy.float128, numpy.complex256 not existing for ARM64 blocks import

### ISSUE THREAD

**Issue by kparasch** [xsuite/xtrack#107]
xobjects cannot be imported on an M1 machine with numpy compiled natively as numpy.float128 and numpy.complex256 do not exist. Long doubles are not supported in the ARM64 architecture.

Should they be removed from xobjects/scalar.py?

**Comment by giadarol** [comment]
They are not used by any of the xsuite packages. I will remove them for now. We can reintroduce them (somehow optionally) in case anybody will need them in the future.

**Comment by giadarol** [comment]
Solved in Xobjects 0.1.6
