### ISSUE TITLE
cpymad requirement blocks native M1 (macos, arm64) installation

### ISSUE THREAD

**Issue by kparasch** [xsuite/xtrack#126]
The fact that xtrack requires xdeps and xdeps requires cpymad blocks the installation of xtrack in a native macos arm64 environment, as cpymad is not yet supported.

**Comment by rdemaria** [comment]
cpymad denpedency can be removed from xdeps for me. Indeed I would probably move the madx specific features of xdeps in another repository if more convenient

**Comment by giadarol** [comment]
In fact there is no direct import of cpymad in xdeps. I just removed the dependency.
