### ISSUE TITLE
Question: particle_ref in json generated from pymask?

### ISSUE THREAD

**Issue by pbelange** [xsuite/xtrack#132]
Sorry to bother you with more requests... 

I noticed that if I want to use `tracker.twiss()`, the line object should have a `.particle_ref` property, like in the example below:
```python
with open(fname_line_particles, 'r') as fid:
    input_data = json.load(fid)
line = xt.Line.from_dict(input_data['line'])
line.particle_ref = xp.Particles.from_dict(input_data['particle'])
```

This property doesn't seem to be created when pymask generates the xsuite line using `pm.generate_xsuite_line`. Do you have any documentation on that so that I could implement it in pymask?

**Comment by giadarol** [comment]
Hi, you are not bothering at all 😀

The data structure generated by the mask is slightly different but should contain all the info.

You could do the following:
```python
fname_line_particles=“line_bb_for_tracking.json”
with open(fname_line_particles, 'r') as fid:
    input_data = json.load(fid)
line = xt.Line.from_dict(input_data)
line.particle_ref = xp.Particles.from_dict(input_data['particle_on_tracker_co'])
```
Let me no io it works

**Comment by pbelange** [comment]
Setting the `line` and `tracker` works with the above, so indeed the `particle_on_tracker_co` key exists in the json, but then `tracker.twiss()` returns an error that I can't really figure out:
```python
File ~/Apps/xtrack/xtrack/twiss_from_tracker.py:214, in twiss_from_tracker(tracker, particle_ref, r_sigma, nemitt_x, nemitt_y, n_theta, delta_disp, delta_chrom, particle_co_guess, steps_r_matrix, co_search_settings, at_elements, at_s, eneloss_and_damping, symplectify)
    211 gemitt_x = nemitt_x/part_on_co._xobject.beta0[0]/part_on_co._xobject.gamma0[0]
    212 gemitt_y = nemitt_y/part_on_co._xobject.beta0[0]/part_on_co._xobject.gamma0[0]
--> 214 W, Winv, Rot = compute_linear_normal_form(RR, symplectify=symplectify)
    216 s = np.array(tracker.line.get_s_elements())
    218 scale_transverse_x = np.sqrt(gemitt_x)*r_sigma

File ~/Apps/xtrack/xtrack/linear_normal_form.py:61, in compute_linear_normal_form(M, symplectify, tol_det_M)
     59     mask_non_zero[ii] = False
     60     if np.sum(mask_non_zero)<1:
---> 61         raise ValueError(
     62             'Invalid one-turn map: No coordinates respond to variations of '
     63             + 'x px y py zeta delta'.split()[ii])
     65 if symplectify:
     66     M = healy_symplectify(M)

ValueError: Invalid one-turn map: No coordinates respond to variations of x
```

**Comment by giadarol** [comment]
Could you please share the json of your line?

**Comment by pbelange** [comment]
**Don't waste your time on this for now...** I will come back to this in a few days, this json was generated with the old version of xtrack and xpart. And now lhcmask was also updated a few hours ago... hard to keep up but I should be able to solve the problem...

**Comment by giadarol** [comment]
OK, keep me posted and if needed I will take a look

**Comment by giadarol** [comment]
I close the issue for now, don't hesitate to reopen if you still see problems
