### ISSUE TITLE
What is psigma ??!!!

### ISSUE THREAD

**Issue by giadarol** [xsuite/xtrack#149]
In some places in the code we assume psigma = (E-E_0)/E_0 but on the manual we write psigma = (E-E_0)/(beta_0 P_0 c)  which is in fact  psigma = (E-E_0)/(beta_0^2 E_0). What's the truth?

**Comment by rdemaria** [comment]
psigma = (E-E_0)/(beta_0 P_0 c) = (E-E_0)/(beta_0^2 E_0)

**Comment by rdemaria** [comment]
psigma is not particularly useful, it originates from the conjugate momentum of sigma = s - beta0 T used in SixTrack. If there are bugs, it seems a good occasion to move to ptau= (E-E_0)/(P_0 c)= (gamma-gamma_0)/(beta_0 gamma_0 c)

**Comment by giadarol** [comment]
Moved to tau (xpart v0.6.0, xtrack v0.11.0)
