### ISSUE TITLE
Dump beam info after number of turns on CPU or store beam parameters only

### ISSUE THREAD

**Issue by VoRodin** [xsuite/xtrack#181]
Hi, 

How it's possible to do this in order to decrease GPU memory usage and still have some info about the beam?

For now, I did it in PyHEADTAIL way:
pyht_beam <= context.nparray_from_context_array(particles.*)
bunch_monitor.dump(pyht_beam)

**Comment by giadarol** [comment]
Hello,
you find here some information on how to save/load particles in different ways:
https://xsuite.readthedocs.io/en/latest/particlesmanip.html#saving-and-loading-particles-objects-to-from-dictionary-or-file

Does it help for your case?

**Comment by VoRodin** [comment]
Hi, 

Yes, it's  quite straightforward solution.

And then during tracking I can simply append one data frame to another.

Thanks!
