### ISSUE TITLE
The xfields dependency is not declared

### ISSUE THREAD

**Issue by fsoubelet** [xsuite/xtrack#395]
When importing anything from `xtrack`, the `__init__.py` is loaded which loads from `xtrack.multiline.multiline` and this module imports `xfields`, which is not declared as a dependency and not installed with `xtrack`.

A simple fix would be to add `xfields` in the dependencies in `setup.py`.

**Comment by giadarol** [comment]
Thanks for spotting this. I don't want xfields to be a hard dependency of xtrack (also to avoid circular dependencies).
Instead I will move the import inside the methods that require xfields, so that the rest of xtrack can be optionally used without xfields. Coming in the next release.

**Comment by giadarol** [comment]
Done
