### ISSUE TITLE
pzeta prints a warning

### ISSUE THREAD

**Issue by pbelange** [xsuite/xtrack#455]
https://github.com/xsuite/xtrack/blob/8d7a2e7682eed93702a7e011b6713b9411fcf402/xtrack/particles/particles.py#L1273-L1278

The `pzeta` calculation should automatically return `nan` for particles with `state==0` without doing the division by `beta0==0`. Current behaviour prints a warning:

Example:
```python
import xtrack as xt

m = xt.ParticlesMonitor(num_particles=2, start_at_turn=0, stop_at_turn=10)

# Reseting monitor data
with m.data._bypass_linked_vars():
    for tt, nn in m._ParticlesClass.per_particle_vars:
        getattr(m.data, nn)[:] = 0

# Accessing pzeta
m.pzeta

-------------------------------
RuntimeWarning: invalid value encountered in divide
  pzeta = self.ptau / self.beta0
  ```

**Comment by giadarol** [comment]
This is expected, beta0 should always have a valid values. You should avoid zeroing that one

**Comment by giadarol** [comment]
And same for gamma0 and p0c

**Comment by pbelange** [comment]
If I am not mistaken, when the monitor is created it has beta0 = 0. And also, when the particle state goes to 0, then beta0 =0 again for the remaining of the turns. Which is why I was proposing to mask with state>0
