### ISSUE TITLE
Reorganise xtrack.Line

### ISSUE THREAD

**Issue by anabramo** [xsuite/xtrack#51]
Currently, xline.Line uses two main lists: elements and element_names. Lattice modification requires synchronous changes to both lists, which can sometimes be tedious and error-prone. Consider using tuples or class instances to tie together the elements and their names for easier lattice processing.

**Comment by giadarol** [comment]
@anabramo it's a very good idea. Feel free to make the modification and open a PR if you wish.

**Comment by giadarol** [comment]
Will be allowed up in #81
