### ISSUE TITLE
Numerical portability

### ISSUE THREAD

**Issue by giadarol** [xsuite/xtrack#64]
Compiled code does not show a cpu dependence. Numpy instead does due to the use of simd intrinsics and usage of optimised blas and lapack libraries:

https://numpy.org/devdocs/reference/simd/simd-optimizations.html

https://numpy.org/doc/stable/user/building.html

To achieve numerical portability (mostly of pymask) we need to compile numpy and scipy with these features disabled and with the reference netlib implementation for blas and lapack.

**Comment by giadarol** [comment]
I manage to compile numpy with no simd flags by doing, on a fresh Miniconda:
```bash 
conda install gcc_linux-64
conda install gxx_linux-64
conda install gfortran_linux-64

git clone git@github.com:numpy/numpy.git --single-branch main
cd main
python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
```

**Comment by giadarol** [comment]
For scipy:

""" bash
mkdir scipysrc
cd scipysrc/
git clone https://github.com/scipy/scipy --single-branch main
cd main
pip install pythran
pip install pybind11
python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
```

**Comment by skostogl** [comment]
# We restart from scratch

wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
bash Miniconda3-py39_4.10.3-Linux-x86_64.sh
source miniconda3/bin/activate

conda install gcc_linux-64
conda install gxx_linux-64
conda install gfortran_linux-64

pip install cython
conda install -c conda-forge blas
conda install -c conda-forge lapack

git clone https://github.com/numpy/numpy.git --single-branch main
cd main
python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
cd ..

mkdir scipysrc
cd scipysrc/
git clone https://github.com/scipy/scipy --single-branch main
cd main
git submodule update --init
pip install pythran
pip install pybind11
python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
cd ..


pip install ruamel.yaml
pip install pandas matplotlib
pip install pyarrow orjson

git clone https://gitlab.cern.ch/abpcomputing/sandbox/tree_maker.git
cd tree_maker
python -m pip install -e .


pip install -e xobjects

git clone https://github.com/xsuite/xline
pip install -e xline

git clone https://github.com/xsuite/xpart
pip install -e xpart

git clone https://github.com/xsuite/xtrack
pip install -e xtrack

git clone https://github.com/xsuite/xfields
pip install -e xfields

**Comment by giadarol** [comment]
Another attempt:

```bash
#CLEAN
export LD_LIBRARY_PATH=


wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
bash Miniconda3-py39_4.10.3-Linux-x86_64.sh
source miniconda3/bin/activate

conda install gcc_linux-64
conda install gxx_linux-64
conda install gfortran_linux-64

pip install cython

conda install -c anaconda openblas

git clone https://github.com/numpy/numpy.git --single-branch main
cd main
NPY_BLAS_ORDER=openblas NPY_LAPACK_ORDER=openblas python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
cd ..

mkdir scipysrc
cd scipysrc/
git clone https://github.com/scipy/scipy --single-branch main
cd main
git submodule update --init
pip install pythran
pip install pybind11
NPY_BLAS_ORDER=openblas NPY_LAPACK_ORDER=openblas python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
cd ..
```

**Comment by giadarol** [comment]
> ## BLAS and LAPACK from netlib
> To avoid CPU-dependent execution we use blas and lapack from netlib using:
> 
> ```
> conda install "libblas=*=*netlib"
> conda install "liblapack=*=*netlib"
> ```
> 
> More info at: https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=mesa
> 
> Here the full recipe:
> 
> ```shell
> #CLEAN
> export LD_LIBRARY_PATH=
> 
> 
> wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
> bash Miniconda3-py39_4.10.3-Linux-x86_64.sh
> source miniconda3/bin/activate
> 
> conda install -c anaconda gcc_linux-64
> conda install -c anaconda gxx_linux-64
> conda install -c anaconda gfortran_linux-64
> 
> pip install cython
> 
> conda install -c conda-forge "libblas=*=*netlib" # should be netlib, no fancy implementations
> conda install -c conda-forge "liblapack=*=*netlib" # should be netlib, no fancy implementations
> # conda install -c conda-forge lapack # should be netlib, no fancy implementations
> 
> git clone https://github.com/numpy/numpy.git --single-branch main
> cd main
> NPY_BLAS_ORDER=blas NPY_LAPACK_ORDER=lapack python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
> cd ..
> 
> mkdir scipysrc
> cd scipysrc/
> git clone https://github.com/scipy/scipy --single-branch main
> cd main
> git submodule update --init
> pip install pythran
> pip install pybind11
> NPY_BLAS_ORDER=blas NPY_LAPACK_ORDER=lapack python setup.py build_ext --cpu-dispatch="none" --cpu-baseline="none" build_clib --cpu-dispatch="none" --cpu-baseline="none" install
> cd ..
> 
> pip install ruamel.yaml
> pip install pandas matplotlib ipython
> pip install pyarrow 
> 
> conda install -c conda-forge orjson 
> 
> 
> pip install cpymad
> 
> git clone https://gitlab.cern.ch/abpcomputing/sandbox/tree_maker.git
> cd tree_maker
> python -m pip install -e .
> cd ..
> 
> git clone https://github.com/xsuite/xobjects
> pip install -e xobjects
> 
> git clone https://github.com/xsuite/xline
> pip install -e xline
> 
> git clone https://github.com/xsuite/xpart
> pip install -e xpart
> 
> git clone https://github.com/xsuite/xtrack
> pip install -e xtrack
> 
> git clone https://github.com/xsuite/xfields
> pip install -e xfields
> ```

This has been successfully tested on CERN HTCondor and on INFN-CNAF cluster.

Recipe reported on Xsuite documentation: https://xsuite.readthedocs.io/en/latest/numericalreproducibility.html
