### ISSUE TITLE
Inheritance of elements

### ISSUE THREAD

**Issue by xbuffat** [xsuite/xtrack#7]
Currently inheritance of elements is not supported as the class name is hard coded in the c code. A workaround might be found on the python side, but the use case is not clear at the moment.

**Comment by giadarol** [comment]
Maybe this could be solved by adding an attribute "c_data_struct_name" in python that can be customised if needed.
Not urgent, but to be kept in mind

**Comment by giadarol** [comment]
Will reopen if this advanced feature is needed in applications
