### ISSUE TITLE
Change of reference momentum

### ISSUE THREAD

**Issue by xbuffat** [xsuite/xtrack#8]
A change of reference momentum is needed to study ramping machines. It will be needed for the muon collider study (featuring re-circulating LINACs and rapid-cycling synchrotrons). To run on GPUs, this feature requires that the reference momentum (and associated parameters) become attributes of the local particles. For the moment a workaround is used by adjusting the reference momentum on the python side.

**Comment by giadarol** [comment]
Reference energy variable are now per-particle by default.

**Comment by giadarol** [comment]
See https://github.com/xsuite/xtrack/commit/c65fcaeb67389d78afc4b91ca2c1595560bfcd5a

**Comment by giadarol** [comment]
Introduced beam element ```RefereceEnergyIncrease``` that increases the reference energy at each passage and updates delta, cpp, etc. accordingly.

An example can be found here:
https://github.com/xsuite/xtrack/blob/main/examples/acceleration/000_acceleration.py

One can clearly see the accelerating bucket:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8049893/127116410-f897d815-951d-4c13-896b-5cd460b9c421.png">
