### ISSUE TITLE
No from_json option for xtrack.Line

### ISSUE THREAD

**Issue by anabramo** [xsuite/xtrack#83]
In Xsuite v0.2, xline.Line is replaced by xtrack.Line, but the from_json constructor is not supported (nor the to_json method). Will those be added or is there an alternative?

**Comment by giadarol** [comment]
Hi, that is intentional. A json can loaded with:
```python
import json
with open(''line.json", "r") as fid:
    line = xtrack.Line.from_dict(json.load(fid))
```

In this way you can load data from json containing other data or use other formats, pickle for example

**Comment by giadarol** [comment]
Documentation updated:
https://xsuite.readthedocs.io/en/latest/v020changes.html
