### ISSUE TITLE
tracker.record_last_track.to_dict() not working anymore

### ISSUE THREAD

**Issue by pbelange** [xsuite/xtrack#94]
On previous versions, the following could be used to convert the tracking results to pd.Dataframe:
`pd.DataFrame(tracker.record_last_track.to_dict()['data'])`

However, `tracker.record_last_track.to_dict()` now returns `TypeError: _monitor_init() got an unexpected keyword argument '_xobject'`

This is using the following context: `context = xo.ContextCpu()`

**Comment by giadarol** [comment]
@pbelange Thanks for reporting this. It's the result of two issues in xobjects and in xpart.
We'll release a fix very soon

**Comment by giadarol** [comment]
Solved. Please update to latest releases (**Xtrack v0.5.1** and Xobjects **Xobjects v0.1.4**).
